//! Admin API handlers
//! 管理员API处理器 - Organized by business domain
//!
//! ## Groups
//! - auth: login.rs
//! - app: app.rs, send.rs, pay.rs
//! - user: user.rs
//! - system: system.rs, set.rs, dict.rs, encryption.rs, extend.rs
//! - cdk: cdk_kami.rs, cdk_group.rs, cdk_user.rs
//! - agent: agent_list.rs, agent_group.rs, agent_cash.rs
//! - finance: goods.rs, order.rs, statistics.rs, fen_event.rs, fen_order.rs
//! - logs: logs.rs
//! - content: notice.rs, message.rs
//! - ver: ver.rs, download.rs
//! - function: function.rs
//! - upload: upload.rs
//! - adm: adm_list.rs
//! - blocklist: blocklist.rs

pub mod adm;
pub mod agent;
pub mod app;
pub mod auth;
pub mod blocklist;
pub mod cdk;
pub mod content;
pub mod finance;
pub mod function;
pub mod logs;
pub mod system;
pub mod upload;
pub mod user;
pub mod ver;
use crate::app::middleware::admin_auth::AdminAuth;
#[cfg(unix)]
use crate::core::flamegraph;
use salvo::Router;

pub fn admin_routes() -> Router {
    Router::with_path("/api/admin")
        // Login - 不需要认证
        .push(Router::with_path("/login").post(auth::login))
        // tokenVerify - 使用skip_verify模式，返回验证结果
        .push(
            Router::with_path("/admin/verify")
                .hoop(AdminAuth::new().skip_verify())
                .get(auth::token_verify),
        )
        // System - 需要认证
        .push(
            Router::with_path("/system/ulogin")
                .hoop(AdminAuth::new())
                .post(system::system::ulogin),
        )
        .push(
            Router::with_path("/system/urefresh")
                .hoop(AdminAuth::new())
                .get(system::system::urefresh),
        )
        .push(
            Router::with_path("/system/uquit")
                .hoop(AdminAuth::new())
                .post(system::system::uquit),
        )
        .push(
            Router::with_path("/system/uinfo")
                .hoop(AdminAuth::new())
                .get(system::system::uinfo),
        )
        .push(
            Router::with_path("/system/clearCache")
                .hoop(AdminAuth::new())
                .post(system::system::clear_cache),
        )
        .push(
            Router::with_path("/system/getSet")
                .hoop(AdminAuth::new())
                .post(system::system::get_set),
        )
        .push(
            Router::with_path("/system/editSet")
                .hoop(AdminAuth::new())
                .post(system::system::edit_set),
        )
        .push(
            Router::with_path("/system/getUserApiRouter")
                .hoop(AdminAuth::new())
                .post(system::system::get_user_api_router),
        )
        .push(
            Router::with_path("/system/editUserApiRouter")
                .hoop(AdminAuth::new())
                .post(system::system::edit_user_api_router),
        )
        .push(
            Router::with_path("/system/switchUserApiRouter")
                .hoop(AdminAuth::new())
                .post(system::system::switch_user_api_router),
        )
        .push(
            Router::with_path("/system/getUserApiCode")
                .hoop(AdminAuth::new())
                .post(system::system::get_user_api_code),
        )
        .push(
            Router::with_path("/system/editUserApiCode")
                .hoop(AdminAuth::new())
                .post(system::system::edit_user_api_code),
        )
        .push(
            Router::with_path("/system/switchUserApiCode")
                .hoop(AdminAuth::new())
                .post(system::system::switch_user_api_code),
        )
        // Dict - 字典数据（不需要认证）
        .push(Router::with_path("/system/dictAll").get(system::dict::dict_all))
        // Notice/Statistics - 需要认证
        .push(
            Router::with_path("/system/notice")
                .hoop(AdminAuth::new())
                .get(system::system::get_notice_list),
        )
        .push(
            Router::with_path("/system/statistics")
                .hoop(AdminAuth::new())
                .get(system::system::get_statistics),
        )
        .push(
            Router::with_path("/system/loginChart")
                .hoop(AdminAuth::new())
                .get(system::system::get_login_chart),
        )
        // 日志接口 - 个人中心
        .push(
            Router::with_path("/system/getLoginLogList")
                .hoop(AdminAuth::new())
                .get(system::system::get_login_log_list),
        )
        .push(
            Router::with_path("/system/getOperationLogList")
                .hoop(AdminAuth::new())
                .get(system::system::get_operation_log_list),
        )
        // 上传图片接口 - 兼容前端API
        .push(
            Router::with_path("/system/uploadImage")
                .hoop(AdminAuth::new())
                .post(upload::upload::img),
        )
        // App - 需要认证
        .push(
            Router::with_path("/app/get")
                .hoop(AdminAuth::new())
                .post(app::app::get_info),
        )
        .push(
            Router::with_path("/app/getInfo")
                .hoop(AdminAuth::new())
                .post(app::app::get_info),
        )
        .push(
            Router::with_path("/app/getUrl")
                .hoop(AdminAuth::new())
                .post(app::app::get_url),
        )
        .push(
            Router::with_path("/app/list")
                .hoop(AdminAuth::new())
                .post(app::app::get_list),
        )
        .push(
            Router::with_path("/app/getInherit")
                .hoop(AdminAuth::new())
                .post(app::app::get_inherit),
        )
        .push(
            Router::with_path("/app/all")
                .hoop(AdminAuth::new())
                .get(app::app::get_all),
        )
        .push(
            Router::with_path("/app/add")
                .hoop(AdminAuth::new())
                .post(app::app::add),
        )
        .push(
            Router::with_path("/app/edit")
                .hoop(AdminAuth::new())
                .post(app::app::edit),
        )
        .push(
            Router::with_path("/app/del")
                .hoop(AdminAuth::new())
                .post(app::app::del),
        )
        .push(
            Router::with_path("/app/send")
                .hoop(AdminAuth::new())
                .get(app::send::get_info),
        )
        .push(
            Router::with_path("/app/pay")
                .hoop(AdminAuth::new())
                .get(app::pay::get_info),
        )
        .push(
            Router::with_path("/app/pay/edit")
                .hoop(AdminAuth::new())
                .post(app::pay::edit),
        )
        // User - 需要认证
        .push(
            Router::with_path("/user/list")
                .hoop(AdminAuth::new())
                .post(user::user::get_list),
        )
        .push(
            Router::with_path("/user/get")
                .hoop(AdminAuth::new())
                .post(user::user::get),
        )
        .push(
            Router::with_path("/user/add")
                .hoop(AdminAuth::new())
                .post(user::user::add),
        )
        .push(
            Router::with_path("/user/award")
                .hoop(AdminAuth::new())
                .post(user::user::award),
        )
        .push(
            Router::with_path("/user/edit")
                .hoop(AdminAuth::new())
                .post(user::user::edit),
        )
        .push(
            Router::with_path("/user/del")
                .hoop(AdminAuth::new())
                .post(user::user::del),
        )
        .push(
            Router::with_path("/user/delall")
                .hoop(AdminAuth::new())
                .post(user::user::del_all),
        )
        .push(
            Router::with_path("/user/getLog")
                .hoop(AdminAuth::new())
                .post(user::user::get_log),
        )
        .push(
            Router::with_path("/user/unbindSn")
                .hoop(AdminAuth::new())
                .post(user::user::unbind_sn),
        )
        // User 个人中心接口
        .push(
            Router::with_path("/user/updateInfo")
                .hoop(AdminAuth::new())
                .post(user::user::update_info),
        )
        .push(
            Router::with_path("/user/modifyPassword")
                .hoop(AdminAuth::new())
                .post(user::user::modify_password),
        )
        // CDK Kami - 需要认证
        .push(
            Router::with_path("/cdkKami/list")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::get_list),
        )
        .push(
            Router::with_path("/cdkKami/add")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::add),
        )
        .push(
            Router::with_path("/cdkKami/edit")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::edit),
        )
        .push(
            Router::with_path("/cdkKami/editState")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::edit_state),
        )
        .push(
            Router::with_path("/cdkKami/del")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::del),
        )
        .push(
            Router::with_path("/cdkKami/delall")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::del_all),
        )
        .push(
            Router::with_path("/cdkKami/outall")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::out_all),
        )
        .push(
            Router::with_path("/cdkKami/getLog")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::get_log),
        )
        .push(
            Router::with_path("/cdkKami/award")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::award),
        )
        .push(
            Router::with_path("/cdkKami/unbindSn")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_kami::unbind_sn),
        )
        .push(
            Router::with_path("/cdkKami/clear")
                .hoop(AdminAuth::new())
                .get(cdk::cdk_kami::clear),
        )
        // Agent - 需要认证
        .push(
            Router::with_path("/agentList/list")
                .hoop(AdminAuth::new())
                .post(agent::agent_list::get_list),
        )
        .push(
            Router::with_path("/agentList/add")
                .hoop(AdminAuth::new())
                .post(agent::agent_list::add),
        )
        .push(
            Router::with_path("/agentList/edit")
                .hoop(AdminAuth::new())
                .post(agent::agent_list::edit),
        )
        .push(
            Router::with_path("/agentList/del")
                .hoop(AdminAuth::new())
                .post(agent::agent_list::del),
        )
        .push(
            Router::with_path("/agentGroup/list")
                .hoop(AdminAuth::new())
                .post(agent::agent_group::get_list),
        )
        .push(
            Router::with_path("/agentGroup/add")
                .hoop(AdminAuth::new())
                .post(agent::agent_group::add),
        )
        .push(
            Router::with_path("/agentGroup/edit")
                .hoop(AdminAuth::new())
                .post(agent::agent_group::edit),
        )
        .push(
            Router::with_path("/agentGroup/del")
                .hoop(AdminAuth::new())
                .post(agent::agent_group::del),
        )
        // CDK Group - 需要认证
        .push(
            Router::with_path("/cdkGroup/get")
                .hoop(AdminAuth::new())
                .get(cdk::cdk_group::get_all_list),
        )
        .push(
            Router::with_path("/cdkGroup/list")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_group::get_list),
        )
        .push(
            Router::with_path("/cdkGroup/add")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_group::add),
        )
        .push(
            Router::with_path("/cdkGroup/edit")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_group::edit),
        )
        .push(
            Router::with_path("/cdkGroup/del")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_group::del),
        )
        .push(
            Router::with_path("/cdkGroup/delall")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_group::del_all),
        )
        // CDK User - 需要认证
        .push(
            Router::with_path("/cdkUser/list")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::get_list),
        )
        .push(
            Router::with_path("/cdkUser/add")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::add),
        )
        .push(
            Router::with_path("/cdkUser/edit")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::edit),
        )
        .push(
            Router::with_path("/cdkUser/editState")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::edit_state),
        )
        .push(
            Router::with_path("/cdkUser/del")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::del),
        )
        .push(
            Router::with_path("/cdkUser/delall")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::del_all),
        )
        .push(
            Router::with_path("/cdkUser/outall")
                .hoop(AdminAuth::new())
                .post(cdk::cdk_user::out_all),
        )
        .push(
            Router::with_path("/cdkUser/clear")
                .hoop(AdminAuth::new())
                .get(cdk::cdk_user::clear),
        )
        // Goods - 需要认证
        .push(
            Router::with_path("/goods/list")
                .hoop(AdminAuth::new())
                .post(finance::goods::get_list),
        )
        .push(
            Router::with_path("/goods/add")
                .hoop(AdminAuth::new())
                .post(finance::goods::add),
        )
        .push(
            Router::with_path("/goods/edit")
                .hoop(AdminAuth::new())
                .post(finance::goods::edit),
        )
        .push(
            Router::with_path("/goods/editState")
                .hoop(AdminAuth::new())
                .post(finance::goods::edit_state),
        )
        .push(
            Router::with_path("/goods/del")
                .hoop(AdminAuth::new())
                .post(finance::goods::del),
        )
        // Order - 需要认证
        .push(
            Router::with_path("/order/list")
                .hoop(AdminAuth::new())
                .post(finance::order::get_list),
        )
        .push(
            Router::with_path("/order/statistics")
                .hoop(AdminAuth::new())
                .post(finance::order::statistics),
        )
        .push(
            Router::with_path("/order/edit")
                .hoop(AdminAuth::new())
                .post(finance::order::edit),
        )
        .push(
            Router::with_path("/order/del")
                .hoop(AdminAuth::new())
                .post(finance::order::del),
        )
        // Statistics - 需要认证
        .push(
            Router::with_path("/statistics/get")
                .hoop(AdminAuth::new())
                .get(finance::statistics::get),
        )
        // Logs - 需要认证
        .push(
            Router::with_path("/logs/list")
                .hoop(AdminAuth::new())
                .post(logs::logs::get_list),
        )
        .push(
            Router::with_path("/logs/list/user")
                .hoop(AdminAuth::new())
                .post(logs::logs::get_list_user),
        )
        .push(
            Router::with_path("/logs/list/admin")
                .hoop(AdminAuth::new())
                .post(logs::logs::get_list_admin),
        )
        .push(
            Router::with_path("/logs/type")
                .hoop(AdminAuth::new())
                .get(logs::logs::get_type),
        )
        .push(
            Router::with_path("/logs/type/user")
                .hoop(AdminAuth::new())
                .get(logs::logs::get_type_user),
        )
        .push(
            Router::with_path("/logs/type/admin")
                .hoop(AdminAuth::new())
                .get(logs::logs::get_type_admin),
        )
        .push(
            Router::with_path("/logs/del")
                .hoop(AdminAuth::new())
                .post(logs::logs::del),
        )
        .push(
            Router::with_path("/logs/delall")
                .hoop(AdminAuth::new())
                .post(logs::logs::del_all),
        )
        .push(
            Router::with_path("/logs/clean")
                .hoop(AdminAuth::new())
                .post(logs::logs::clean),
        )
        // Fen Order - 需要认证
        .push(
            Router::with_path("/fenOrder/list")
                .hoop(AdminAuth::new())
                .post(finance::fen_order::get_list),
        )
        .push(
            Router::with_path("/fenOrder/edit")
                .hoop(AdminAuth::new())
                .post(finance::fen_order::edit),
        )
        .push(
            Router::with_path("/fenOrder/del")
                .hoop(AdminAuth::new())
                .post(finance::fen_order::del),
        )
        .push(
            Router::with_path("/fenOrder/delall")
                .hoop(AdminAuth::new())
                .post(finance::fen_order::delall),
        )
        // Fen Event - 需要认证
        .push(
            Router::with_path("/fenEvent/list")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::get_list),
        )
        .push(
            Router::with_path("/fenEvent/add")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::add),
        )
        .push(
            Router::with_path("/fenEvent/edit")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::edit),
        )
        .push(
            Router::with_path("/fenEvent/editState")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::edit_state),
        )
        .push(
            Router::with_path("/fenEvent/del")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::del),
        )
        .push(
            Router::with_path("/fenEvent/delall")
                .hoop(AdminAuth::new())
                .post(finance::fen_event::del_all),
        )
        // Notice - 需要认证
        .push(
            Router::with_path("/notice/list")
                .hoop(AdminAuth::new())
                .post(content::notice::get_list),
        )
        .push(
            Router::with_path("/notice/add")
                .hoop(AdminAuth::new())
                .post(content::notice::add),
        )
        .push(
            Router::with_path("/notice/edit")
                .hoop(AdminAuth::new())
                .post(content::notice::edit),
        )
        .push(
            Router::with_path("/notice/del")
                .hoop(AdminAuth::new())
                .post(content::notice::del),
        )
        // Message - 需要认证
        .push(
            Router::with_path("/message/list")
                .hoop(AdminAuth::new())
                .post(content::message::get_list),
        )
        .push(
            Router::with_path("/message/edit")
                .hoop(AdminAuth::new())
                .post(content::message::edit),
        )
        .push(
            Router::with_path("/message/del")
                .hoop(AdminAuth::new())
                .post(content::message::del),
        )
        // Set - 需要认证
        .push(
            Router::with_path("/set/list")
                .hoop(AdminAuth::new())
                .post(system::set::get_list),
        )
        .push(
            Router::with_path("/set/edit")
                .hoop(AdminAuth::new())
                .post(system::set::edit),
        )
        // Ver - 需要认证
        .push(
            Router::with_path("/ver/get")
                .hoop(AdminAuth::new())
                .post(ver::ver::get_list),
        )
        .push(
            Router::with_path("/ver/list")
                .hoop(AdminAuth::new())
                .post(ver::ver::get_list),
        )
        .push(
            Router::with_path("/ver/submit")
                .hoop(AdminAuth::new())
                .post(ver::ver::submit),
        )
        .push(
            Router::with_path("/ver/add")
                .hoop(AdminAuth::new())
                .post(ver::ver::add),
        )
        .push(
            Router::with_path("/ver/edit")
                .hoop(AdminAuth::new())
                .post(ver::ver::edit),
        )
        .push(
            Router::with_path("/ver/del")
                .hoop(AdminAuth::new())
                .post(ver::ver::del),
        )
        .push(
            Router::with_path("/ver/delall")
                .hoop(AdminAuth::new())
                .post(ver::ver::del_all),
        )
        .push(
            Router::with_path("/ver/discard")
                .hoop(AdminAuth::new())
                .post(ver::ver::discard),
        )
        .push(
            Router::with_path("/ver/milist")
                .hoop(AdminAuth::new())
                .get(ver::ver::get_milist),
        )
        .push(
            Router::with_path("/ver/group")
                .hoop(AdminAuth::new())
                .get(ver::ver::get_group),
        )
        // Extend - 需要认证
        .push(
            Router::with_path("/extend/list")
                .hoop(AdminAuth::new())
                .post(system::extend::get_list),
        )
        .push(
            Router::with_path("/extend/add")
                .hoop(AdminAuth::new())
                .post(system::extend::add),
        )
        .push(
            Router::with_path("/extend/edit")
                .hoop(AdminAuth::new())
                .post(system::extend::edit),
        )
        .push(
            Router::with_path("/extend/del")
                .hoop(AdminAuth::new())
                .post(system::extend::del),
        )
        // Agent Cash - 需要认证
        .push(
            Router::with_path("/agentCash/list")
                .hoop(AdminAuth::new())
                .post(agent::agent_cash::get_list),
        )
        .push(
            Router::with_path("/agentCash/edit")
                .hoop(AdminAuth::new())
                .post(agent::agent_cash::edit),
        )
        .push(
            Router::with_path("/agentCash/del")
                .hoop(AdminAuth::new())
                .post(agent::agent_cash::del),
        )
        // Download - 需要认证
        .push(
            Router::with_path("/download/index")
                .hoop(AdminAuth::new())
                .post(ver::download::index),
        )
        // Upload - 需要认证
        .push(
            Router::with_path("/upload/index")
                .hoop(AdminAuth::new())
                .post(upload::upload::index),
        )
        .push(
            Router::with_path("/upload/img")
                .hoop(AdminAuth::new())
                .post(upload::upload::img),
        )
        // Encryption - 需要认证
        .push(
            Router::with_path("/encryption/plug")
                .hoop(AdminAuth::new())
                .get(system::encryption::get_plug),
        )
        .push(
            Router::with_path("/encryption/list")
                .hoop(AdminAuth::new())
                .post(system::encryption::get_list),
        )
        .push(
            Router::with_path("/encryption/submit")
                .hoop(AdminAuth::new())
                .post(system::encryption::submit),
        )
        .push(
            Router::with_path("/encryption/add")
                .hoop(AdminAuth::new())
                .post(system::encryption::add),
        )
        .push(
            Router::with_path("/encryption/edit")
                .hoop(AdminAuth::new())
                .post(system::encryption::edit),
        )
        .push(
            Router::with_path("/encryption/editSign")
                .hoop(AdminAuth::new())
                .post(system::encryption::edit_sign),
        )
        .push(
            Router::with_path("/encryption/del")
                .hoop(AdminAuth::new())
                .post(system::encryption::del),
        )
        // Function - 需要认证
        .push(
            Router::with_path("/functions/list")
                .hoop(AdminAuth::new())
                .post(function::function::get_list),
        )
        .push(
            Router::with_path("/functions/getInfo")
                .hoop(AdminAuth::new())
                .post(function::function::get_info),
        )
        .push(
            Router::with_path("/functions/getCode")
                .hoop(AdminAuth::new())
                .post(function::function::get_code),
        )
        .push(
            Router::with_path("/functions/add")
                .hoop(AdminAuth::new())
                .post(function::function::add),
        )
        .push(
            Router::with_path("/functions/edit")
                .hoop(AdminAuth::new())
                .post(function::function::edit),
        )
        .push(
            Router::with_path("/functions/editState")
                .hoop(AdminAuth::new())
                .post(function::function::edit_state),
        )
        .push(
            Router::with_path("/functions/del")
                .hoop(AdminAuth::new())
                .post(function::function::del),
        )
        // Send - 需要认证
        .push(
            Router::with_path("/send")
                .hoop(AdminAuth::new())
                .get(app::send::get_info),
        )
        .push(
            Router::with_path("/send/getInfo")
                .hoop(AdminAuth::new())
                .post(app::send::get_info),
        )
        .push(
            Router::with_path("/send/edit")
                .hoop(AdminAuth::new())
                .post(app::send::edit),
        )
        // Admin List - 需要认证
        .push(
            Router::with_path("/admList/list")
                .hoop(AdminAuth::new())
                .post(adm::adm_list::get_list),
        )
        .push(
            Router::with_path("/admList/add")
                .hoop(AdminAuth::new())
                .post(adm::adm_list::add),
        )
        .push(
            Router::with_path("/admList/edit")
                .hoop(AdminAuth::new())
                .post(adm::adm_list::edit),
        )
        .push(
            Router::with_path("/admList/del")
                .hoop(AdminAuth::new())
                .post(adm::adm_list::del),
        )
        .push(
            Router::with_path("/admin/setAvatars")
                .hoop(AdminAuth::new())
                .post(adm::adm_list::set_avatars),
        )
        // Blocklist - 需要认证
        .push(
            Router::with_path("/blocklist/list")
                .hoop(AdminAuth::new())
                .post(blocklist::blocklist::get_list),
        )
        .push(
            Router::with_path("/blocklist/add")
                .hoop(AdminAuth::new())
                .post(blocklist::blocklist::add),
        )
        .push(
            Router::with_path("/blocklist/edit")
                .hoop(AdminAuth::new())
                .post(blocklist::blocklist::edit),
        )
        .push(
            Router::with_path("/blocklist/del")
                .hoop(AdminAuth::new())
                .post(blocklist::blocklist::del),
        )
        .push(
            Router::with_path("/blocklist/delall")
                .hoop(AdminAuth::new())
                .post(blocklist::blocklist::del_all),
        )
        // Flamegraph - 火焰图性能分析（需要认证，仅 Unix 平台）
        .push({
            #[cfg(unix)]
            {
                Router::new()
                    .push(
                        Router::with_path("/flamegraph/start")
                            .hoop(AdminAuth::new())
                            .post(flamegraph::flame_start),
                    )
                    .push(
                        Router::with_path("/flamegraph/stop")
                            .hoop(AdminAuth::new())
                            .post(flamegraph::flame_stop),
                    )
                    .push(
                        Router::with_path("/flamegraph/status")
                            .hoop(AdminAuth::new())
                            .get(flamegraph::flame_status),
                    )
                    .push(
                        Router::with_path("/flamegraph/svg")
                            .hoop(AdminAuth::new())
                            .get(flamegraph::flame_svg),
                    )
                    .push(
                        Router::with_path("/flamegraph/pprof")
                            .hoop(AdminAuth::new())
                            .get(flamegraph::flame_pprof),
                    )
                    .push(
                        Router::with_path("/flamegraph/auto")
                            .hoop(AdminAuth::new())
                            .post(flamegraph::flame_auto_profile),
                    )
            }
            #[cfg(not(unix))]
            {
                Router::new()
            }
        })
        // 更新日志 - 个人中心
        .push(
            Router::with_path("/uplog")
                .hoop(AdminAuth::new())
                .get(ver::ver::get_uplog),
        )
}
